<?php declare(strict_types=1);

$texts = [
    'site.title'                                                    => 'Feedr',
    'site.version'                                                  => '2.0.0',

    'nav.hamburger.screenreader'                                    => 'Toggle navigation',
    'nav.user.member-since.%'                                       => 'Member since %s',
    'nav.logout.submit'                                             => 'Sign out',
    'nav.sidebar.search.placeholder'                                => 'Search...',
    'nav.sidebar.main.title'                                        => 'MAIN NAVIGATION',
    'nav.sidebar.main.items.dashboard'                              => 'Dashboard',
    'nav.sidebar.main.items.feeds'                                  => 'Feeds',
    'nav.sidebar.main.items.feeds.create'                           => 'Create feed',
    'nav.sidebar.main.items.feeds.yours'                            => 'Your feeds',
    'nav.sidebar.main.items.statistics'                             => 'Statistics',
    'nav.sidebar.main.items.notifications'                          => 'Notifications',
    'nav.sidebar.main.items.notifications.requests'                 => 'Requests',
    'nav.sidebar.main.items.notifications.added'                    => 'Added to feed',
    'nav.sidebar.admin.title'                                       => 'ADMIN',
    'nav.sidebar.admin.items.users'                                 => 'Users',
    'nav.sidebar.admin.items.errors'                                => 'Errors',

    'breadcrumbs.home'                                              => 'Home',
    'breadcrumbs.feeds'                                             => 'Feeds',

    'footer.version.title'                                          => 'Version',
    'footer.theme.author'                                           => 'Theme by <a href="http://almsaeedstudio.com/" target="_blank">Almsaeed Studio</a>.',
    'footer.theme.license'                                          => 'MIT licensed.',
    'footer.project.github.%'                                       => 'Fork me on <a href="%s" target="_blank">GitHub</a>.',

    'page.not-found.title'                                          => '404',
    'page.not-found.sub-title'                                      => 'Oops! Page not found.',
    'page.not-found.description'                                    => 'We could not find the page you were looking for. Are you sure you have access to the page? Try to find a feed by using the search form.',
    'page.not-found.search.placeholder'                             => 'Search',

    'page.error.title'                                              => 'Err..',
    'page.error.sub-title'                                          => 'Eeeeek! Something went wrong.',
    'page.error.description'                                        => 'This shouldn\'t happen. No idea what happened. Try applying palm to face or try to find a feed by using the search form.',
    'page.error.search.placeholder'                                 => 'Search',

    'page.login.title'                                              => 'Login',
    'page.login.button'                                             => 'Sign In using GitHub',
    'page.login.privacy'                                            => 'We only use GitHub data to authenticate you and retrieve your GitHub id.',

    'page.dashboard.title'                                          => 'Dashboard',
    'page.dashboard.version'                                        => 'Version',
    'page.dashboard.feeds.title'                                    => 'Feeds',
    'page.dashboard.feeds.column.name'                              => 'Name',
    'page.dashboard.feeds.column.posts'                             => 'Posts',
    'page.dashboard.feeds.column.admins'                            => 'Admins',
    'page.dashboard.feeds.column.requests'                          => 'Requests',
    'page.dashboard.feeds.column.statistics'                        => 'Statistics',
    'page.dashboard.feeds.column.url'                               => 'URL',
    'page.dashboard.feeds.new'                                      => 'Create new feed',
    'page.dashboard.feeds.all'                                      => 'View all feeds',
    'page.dashboard.feed.switch.title'                              => 'Change feed',
    'page.dashboard.feed.filter.placeholder'                        => 'Type keywords ...',
    'page.dashboard.feed.filter.submit'                             => 'Filter',
    'page.dashboard.notifications.title'                            => 'Notifications',
    'page.dashboard.notifications.login'                            => 'Login',
    'page.dashboard.notifications.requested'                        => 'Feed requested',
    'page.dashboard.notifications.view-more'                        => 'View more notifications',

    'page.feeds.create.title'                                       => 'Feeds',
    'page.feeds.create.subtitle'                                    => 'Create new feed',
    'page.feeds.create.form.basic.title'                            => 'New feed information',
    'page.feeds.create.form.basic.name.label'                       => 'Feed name:',
    'page.feeds.create.form.basic.visibility.options.public'        => 'Public',
    'page.feeds.create.form.basic.visibility.options.private'       => 'Private',
    'page.feeds.create.form.basic.password.label'                   => 'Password:',
    'page.feeds.create.form.basic.password2.label'                  => 'Repeat password:',
    'page.feeds.create.form.repos.title'                            => 'Repositories',
    'page.feeds.create.form.repos.add.placeholder'                  => 'Add new repository...',
    'page.feeds.create.form.repos.amount.%'                         => '%d repositories in this feed',
    'page.feeds.create.form.repos.table.username.heading'           => 'Username',
    'page.feeds.create.form.repos.table.repository.heading'         => 'Repository',
    'page.feeds.create.form.repos.table.url.heading'                => 'URL',
    'page.feeds.create.form.repos.table.delete.heading'             => 'Delete',
    'page.feeds.create.form.admins.title'                           => 'Administrators',
    'page.feeds.create.form.admins.add.placeholder'                 => 'Add new admin...',
    'page.feeds.create.form.admins.amount.%'                        => '%d administrators in this feed',
    'page.feeds.create.form.admins.table.avatar.heading'            => 'Avatar',
    'page.feeds.create.form.admins.table.username.heading'          => 'Username',
    'page.feeds.create.form.admins.table.url.heading'               => 'URL',
    'page.feeds.create.form.admins.table.delete.heading'            => 'Delete',
    'page.feeds.create.preview.title'                               => 'Feed preview',
    'page.feeds.create.form.basic.visibility.label'                 => 'Visibility:',
    'page.feeds.create.form.submit'                                 => 'Save',

    'modal.repositories.search.result.title'                        => 'Found repositories',
    'modal.repositories.search.result.empty'                        => 'No repositories were found.',
    'modal.repositories.search.result.close'                        => 'Close',

    'modal.administrators.search.result.title'                      => 'Found administrators',
    'modal.administrators.search.result.empty'                      => 'No users were found.',
    'modal.administrators.search.result.close'                      => 'Close',

    'feeds.preview.empty'                                           => 'No repositories selected yet or none of the repositories have GitHub releases.',
];
