<?php declare(strict_types=1);

$texts = [
    'site.title'                                                    => 'Feedr',
    'site.version'                                                  => '2.0.0',

    'nav.hamburger.screenreader'                                    => 'Toggle navigation',
    'nav.user.member-since.%'                                       => 'Member since %s',
    'nav.logout.submit'                                             => 'Sign out',
    'nav.sidebar.search.placeholder'                                => 'Search...',
    'nav.sidebar.main.title'                                        => 'MAIN NAVIGATION',
    'nav.sidebar.main.items.dashboard'                              => 'Dashboard',
    'nav.sidebar.main.items.feeds'                                  => 'Feeds',
    'nav.sidebar.main.items.feeds.yours'                            => 'Your feeds',
    'nav.sidebar.main.items.feeds.popular'                          => 'Popular feeds',
    'nav.sidebar.main.items.statistics'                             => 'Statistics',
    'nav.sidebar.main.items.notifications'                          => 'Notifications',
    'nav.sidebar.main.items.notifications.requests'                 => 'Requests',
    'nav.sidebar.main.items.notifications.added'                    => 'Added to feed',
    'nav.sidebar.admin.title'                                       => 'ADMIN',
    'nav.sidebar.admin.items.users'                                 => 'Users',
    'nav.sidebar.admin.items.errors'                                => 'Errors',

    'breadcrumbs.home'                                              => 'Home',

    'footer.version.title'                                          => 'Version',
    'footer.theme.author'                                           => 'Theme by <a href="http://almsaeedstudio.com/" target="_blank">Almsaeed Studio</a>.',
    'footer.theme.license'                                          => 'MIT licensed.',
    'footer.project.github.%'                                       => 'Fork me on <a href="%s" target="_blank">GitHub</a>.',

    'page.not-found.title'                                          => '404',
    'page.not-found.sub-title'                                      => 'Oops! Page not found.',
    'page.not-found.description'                                    => 'We could not find the page you were looking for. Are you sure you have access to the page? Try to find a feed by using the search form.',
    'page.not-found.search.placeholder'                             => 'Search',

    'page.error.title'                                              => 'Err..',
    'page.error.sub-title'                                          => 'Eeeeek! Something went wrong.',
    'page.error.description'                                        => 'This shouldn\'t happen. No idea what happened. Try applying palm to face or try to find a feed by using the search form.',
    'page.error.search.placeholder'                                 => 'Search',

    'page.login.title'                                              => 'Login',
    'page.login.button'                                             => 'Sign In using GitHub',
    'page.login.privacy'                                            => 'We only use GitHub data to authenticate you and retrieve your GitHub id.',

    'page.dashboard.title'                                          => 'Dashboard',
    'page.dashboard.version'                                        => 'Version',
    'page.dashboard.feeds.title'                                    => 'Feeds',
    'page.dashboard.feeds.column.name'                              => 'Name',
    'page.dashboard.feeds.column.posts'                             => 'Posts',
    'page.dashboard.feeds.column.admins'                            => 'Admins',
    'page.dashboard.feeds.column.requests'                          => 'Requests',
    'page.dashboard.feeds.column.statistics'                        => 'Statistics',
    'page.dashboard.feeds.column.url'                               => 'URL',
    'page.dashboard.feeds.new'                                      => 'Create new feed',
    'page.dashboard.feeds.all'                                      => 'View all feeds',
    'page.dashboard.feed.switch.title'                              => 'Change feed',
    'page.dashboard.feed.filter.placeholder'                        => 'Type keywords ...',
    'page.dashboard.feed.filter.submit'                             => 'Filter',
    'page.dashboard.notifications.title'                            => 'Notifications',
    'page.dashboard.notifications.requested'                        => 'Feed requested',
    'page.dashboard.notifications.view-more'                        => 'View more notifications',
];
