<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Feedr v1.0</a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <form action="/logout" method="post" class="logout-form">
                    <input type="hidden" name="csrf-token" value="<?php echo htmlspecialchars($this->csrfToken->get(), ENT_QUOTES, 'UTF-8'); ?>">
                    <button class="btn-block"><i class="fa fa-sign-out fa-fw"></i> Logout</button>
                </form>
            </li>
        </ul>
    </li>
</ul>