<?php declare(strict_types=1); ?>
<div class="content-wrapper <?php if (!$this->user->isLoggedIn()) echo 'full-width'; ?>">
    <section class="content">
        <div class="error-page">
            <h1 class="headline text-red"> <?= $this->translate('page.error.title'); ?></h1>
            <div class="error-content">
                <h3><i class="fa fa-warning text-red"></i> <?= $this->translate('page.error.sub-title'); ?></h3>
                <p><?= $this->translate('page.error.description'); ?></p>
                <form class="search-form">
                    <div class="input-group">
                        <input type="text" name="search" class="form-control" placeholder="<?= $this->translate('page.error.search.placeholder'); ?>">
                        <div class="input-group-btn">
                            <button type="submit" name="submit" class="btn btn-danger btn-flat"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
