<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <?php require __DIR__ . '/navigation/top.phtml'; ?>
        <?php //require __DIR__ . '/navigation/side.phtml'; ?>
    </nav>
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Edit feed</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <form action="/feeds/<?php echo $this->feed['id']; ?>/<?php echo $this->url->slugify(htmlspecialchars($this->feed['name'], ENT_QUOTES, 'UTF-8')); ?>" method="post" role="form">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Basic Information
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="input-name">Name</label>
                                        <input class="form-control" name="name" id="input-name" value="<?php echo htmlspecialchars($this->feed['name'], ENT_QUOTES, 'UTF-8'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Repositories
                            <div class="pull-right">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Actions
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="#" data-toggle="modal" data-target="#addRepo">Add repository</a></li>
                                    </ul>
                                    <div class="modal fade" id="addRepo" tabindex="-1" role="dialog" aria-labelledby="addRepoLabel" aria-hidden="true" style="display: none;">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h4 class="modal-title">Add repository</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="form-group input-group">
                                                        <input class="form-control" name="repo" placeholder="Type the URL or name of the repository you would like to add">
                                                        <span class="input-group-btn">
                                                            <button class="btn btn-default" type="button" data-action="repoSearch"><i class="fa fa-search"></i></button>
                                                        </span>
                                                    </div>
                                                    <table class="table table-striped table-bordered table-hover vertical-center" style="display: none;">
                                                        <thead>
                                                            <tr>
                                                                <th>&nbsp;</th>
                                                                <th>Repository</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                    <button type="button" class="btn btn-primary" data-action="modalAddRepo">Add</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover vertical-center" id="repos-table">
                                    <thead>
                                        <tr>
                                            <th>Username</th>
                                            <th>Repository</th>
                                            <th>URL</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->feed['repos'] as $repo) { ?>
                                            <tr class="odd" data-id="<?php echo $repo['repository_id']; ?>" data-fullname="<?php echo htmlspecialchars($repo['repository'], ENT_QUOTES, 'UTF-8'); ?>">
                                                <?php list($userName, $repoName) = explode('/', $repo['repository']); ?>
                                                <td><?php echo htmlspecialchars($userName, ENT_QUOTES, 'UTF-8'); ?></td>
                                                <td><?php echo htmlspecialchars($repoName, ENT_QUOTES, 'UTF-8'); ?></td>
                                                <td><a href="https://github.com/<?php echo htmlspecialchars($repo['repository'], ENT_QUOTES, 'UTF-8'); ?>" target="_blank">https://github.com/<?php echo htmlspecialchars($repo['repository'], ENT_QUOTES, 'UTF-8'); ?></a></td>
                                                <td>
                                                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteRepo<?php echo $repo['repository_id']; ?>">Delete</button>
                                                    <div class="modal fade" id="deleteRepo<?php echo $repo['repository_id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteRepo<?php echo $repo['repository_id']; ?>Label" aria-hidden="true" style="display: none;">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                                    <h4 class="modal-title">Delete repository</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    Are you sure you want to delete the repository (<?php echo $repo['repository']; ?>) from the feed?
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                                    <button type="button" class="btn btn-primary" data-action="deleteRepo" data-id="<?php echo $repo['repository_id']; ?>">Delete</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Administrators
                            <div class="pull-right">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Actions
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="#" data-toggle="modal" data-target="#addAdmin">Add administrator</a></li>
                                    </ul>
                                    <div class="modal fade" id="addAdmin" tabindex="-1" role="dialog" aria-labelledby="addAdminLabel" aria-hidden="true" style="display: none;">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h4 class="modal-title">Add administrator</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="form-group input-group">
                                                        <input class="form-control" name="user" placeholder="Type the name of the user to add as an administrator">
                                                        <span class="input-group-btn">
                                                            <button class="btn btn-default" type="button" data-action="userSearch"><i class="fa fa-search"></i></button>
                                                        </span>
                                                    </div>
                                                    <table class="table table-striped table-bordered table-hover vertical-center" style="display: none;">
                                                        <thead>
                                                            <tr>
                                                                <th>&nbsp;</th>
                                                                <th>Avatar</th>
                                                                <th>Username</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                    <button type="button" class="btn btn-primary" data-action="modalAddAdmin">Add</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover vertical-center" id="admins-table">
                                    <thead>
                                        <tr>
                                            <th>Avatar</th>
                                            <th>Username</th>
                                            <th>URL</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="odd" data-id="<?php echo htmlspecialchars($this->user->get('id'), ENT_QUOTES, 'UTF-8'); ?>" data-username="<?php echo htmlspecialchars($this->user->get('login'), ENT_QUOTES, 'UTF-8'); ?>">
                                            <td><img src="<?php echo htmlspecialchars($this->user->get('avatar_url'), ENT_QUOTES, 'UTF-8'); ?>" class="img-circle"></td>
                                            <td><?php echo htmlspecialchars($this->user->get('login'), ENT_QUOTES, 'UTF-8'); ?> (you)</td>
                                            <td><a href="<?php echo htmlspecialchars($this->user->get('html_url'), ENT_QUOTES, 'UTF-8'); ?>" target="_blank"><?php echo htmlspecialchars($this->user->get('html_url'), ENT_QUOTES, 'UTF-8'); ?></a></td>
                                            <td>
                                                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteAdmin<?php echo htmlspecialchars($this->user->get('id'), ENT_QUOTES, 'UTF-8'); ?>">Delete</button>
                                                <div class="modal fade" id="deleteAdmin<?php echo htmlspecialchars($this->user->get('id'), ENT_QUOTES, 'UTF-8'); ?>" tabindex="-1" role="dialog" aria-labelledby="deleteAdmin<?php echo htmlspecialchars($this->user->get('id'), ENT_QUOTES, 'UTF-8'); ?>Label" aria-hidden="true" style="display: none;">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                                <h4 class="modal-title">Delete administrator</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                Are you sure you want to remove the administrator (<?php echo htmlspecialchars($this->user->get('login'), ENT_QUOTES, 'UTF-8'); ?>) from the feed?
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                                <button type="button" class="btn btn-primary" data-action="deleteAdmin" data-id="<?php echo htmlspecialchars($this->user->get('id'), ENT_QUOTES, 'UTF-8'); ?>">Delete</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <?php foreach ($this->feed['admins'] as $admin) { ?>
                                            <?php if ($admin['id'] == $this->user->get('id')) continue; ?>
                                            <tr class="odd" data-id="<?php echo htmlspecialchars($admin['id'], ENT_QUOTES, 'UTF-8'); ?>" data-username="<?php echo htmlspecialchars($admin['username'], ENT_QUOTES, 'UTF-8'); ?>">
                                                <td><img src="https://avatars.githubusercontent.com/u/<?php echo htmlspecialchars($admin['id'], ENT_QUOTES, 'UTF-8'); ?>?v=3" class="img-circle"></td>
                                                <td><?php echo htmlspecialchars($admin['username'], ENT_QUOTES, 'UTF-8'); ?></td>
                                                <td><a href="https://github.com/<?php echo htmlspecialchars($admin['username'], ENT_QUOTES, 'UTF-8'); ?>" target="_blank">https://github.com/<?php echo htmlspecialchars($admin['username'], ENT_QUOTES, 'UTF-8'); ?></a></td>
                                                <td>
                                                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteAdmin<?php echo htmlspecialchars($admin['id'], ENT_QUOTES, 'UTF-8'); ?>">Delete</button>
                                                    <div class="modal fade" id="deleteAdmin<?php echo htmlspecialchars($admin['id'], ENT_QUOTES, 'UTF-8'); ?>" tabindex="-1" role="dialog" aria-labelledby="deleteAdmin<?php echo htmlspecialchars($admin['id'], ENT_QUOTES, 'UTF-8'); ?>Label" aria-hidden="true" style="display: none;">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                                    <h4 class="modal-title">Delete administrator</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    Are you sure you want to remove the administrator (<?php echo htmlspecialchars($admin['username'], ENT_QUOTES, 'UTF-8'); ?>) from the feed?
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                                    <button type="button" class="btn btn-primary" data-action="deleteAdmin" data-id="<?php echo htmlspecialchars($admin['id'], ENT_QUOTES, 'UTF-8'); ?>">Delete</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="repos" value="<?php echo htmlspecialchars($this->jsonRepos, ENT_QUOTES, 'UTF-8'); ?>">
                    <input type="hidden" name="admins" value="<?php echo htmlspecialchars(json_encode($this->feed['admins']), ENT_QUOTES, 'UTF-8'); ?>">
                    <button type="submit" class="btn btn-default">Save</button>
                    <button type="reset" class="btn btn-default">Cancel</button>
                </form>
            </div>
            <!-- /.col-lg-8 -->
            <div class="col-lg-4">
                <div class="chat-panel panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-comments fa-fw"></i>
                        Feed preview
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <ul class="chat preview">
                            <li class="clearfix loader"><img src="/images/ajax-loader.gif"></li>
                            <li class="left clearfix empty" style="display: none;">
                                <span class="chat-img pull-left">
                                    <img src="/images/github_icon.png" alt="GitHub Release" class="img-circle">
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <small class="pull-right text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> 0 mins ago</small>
                                        <strong class="pull-left primary-font">No repositories added</strong>
                                    </div>
                                    <p>
                                        Add repositories to see the preview of the feed
                                    </p>
                                </div>
                            </li>
                            <?php foreach ($this->feed['posts'] as $index => $post) { ?>
                                <li class="<?php echo ['left', 'right'][$index % 2]; ?> clearfix new-item" style="display: block;">
                                    <span class="chat-img pull-<?php echo ['left', 'right'][$index % 2]; ?>">
                                        <img src="<?php echo htmlspecialchars($post['avatar_url'], ENT_QUOTES, 'UTF-8'); ?>" alt="GitHub Release" class="img-circle">
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font pull-<?php echo ['left', 'right'][$index % 2]; ?>"><a href="<?php echo htmlspecialchars($post['url'], ENT_QUOTES, 'UTF-8'); ?>" target="_blank"><?php echo htmlspecialchars($post['repository'], ENT_QUOTES, 'UTF-8'); ?> <?php echo htmlspecialchars($post['version'], ENT_QUOTES, 'UTF-8'); ?></a></strong>
                                            <small class="pull-<?php echo ['right', 'left'][$index % 2]; ?> text-muted">
                                                <i class="fa fa-clock-o fa-fw"></i> <?php echo $post['timestamp']; ?>
                                            </small>
                                        </div>
                                        <p>
                                            <?php echo htmlspecialchars($post['content'], ENT_QUOTES, 'UTF-8'); ?>
                                        </p>
                                    </div>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
