<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <?php require __DIR__ . '/navigation/top.phtml'; ?>
        <?php //require __DIR__ . '/navigation/side.phtml'; ?>
    </nav>
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Dashboard</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-rss fa-fw"></i> Feeds
                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    Actions
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="/create">Add feed</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Posts</th>
                                        <th>Admins</th>
                                        <th>Requests</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $i = 0; foreach ($this->feeds as $feed) { $i++ ?>
                                        <tr class="<?php echo ['odd', 'even'][$i%2]; ?>">
                                            <td><?php echo htmlspecialchars($feed['name'], ENT_QUOTES, 'UTF-8'); ?></td>
                                            <td><?php echo $feed['posts']; ?></td>
                                            <td><?php echo count($feed['admins']); ?></td>
                                            <td>#</td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.panel -->
                <div class="chat-panel panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-comments fa-fw"></i>
                        Feed (Room 11 Regulars Releases)
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-chevron-down"></i>
                            </button>
                            <ul class="dropdown-menu slidedown">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-check-circle fa-fw"></i> Room 11 Regulars Releases
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-check-circle fa-fw"></i> Room 17 Regulars Releases
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-times fa-fw"></i> Test Feed
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <ul class="chat">
                            <li class="left clearfix">
                                <span class="chat-img pull-left">
                                    <img src="/images/github_icon.png" alt="GitHub Rlease" class="img-circle">
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <strong class="primary-font">Ardent 1.0.0 - rdlowrey</strong>
                                        <small class="pull-right text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> 12 mins ago
                                        </small>
                                    </div>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                                    </p>
                                </div>
                            </li>
                            <li class="right clearfix">
                                <span class="chat-img pull-right">
                                    <img src="/images/github_icon.png" alt="GitHub Rlease" class="img-circle">
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <small class=" text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> 13 mins ago</small>
                                        <strong class="pull-right primary-font">Bastion v0.5.1 - Danack</strong>
                                    </div>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                                    </p>
                                </div>
                            </li>
                            <li class="left clearfix">
                                <span class="chat-img pull-left">
                                    <img src="/images/github_icon.png" alt="GitHub Rlease" class="img-circle">
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <strong class="primary-font">PasswordLib v1.2.1 - ircmaxell</strong>
                                        <small class="pull-right text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> 14 mins ago</small>
                                    </div>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                                    </p>
                                </div>
                            </li>
                            <li class="right clearfix">
                                <span class="chat-img pull-right">
                                    <img src="https://avatars.githubusercontent.com/u/1330296?v=3" alt="GitHub Rlease" class="img-circle">
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <small class=" text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> 15 mins ago</small>
                                        <strong class="pull-right primary-font">OpCacheGUI v1.0.0-rc5 - PeeHaa</strong>
                                    </div>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                                    </p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php
            $logTypes = [
                'newPost' => [
                    'icon' => 'fa-comment',
                    'text' => 'New Post',
                ],
                'newFeed' => [
                    'icon' => 'fa-rss',
                    'text' => 'New Feed',
                ],
                'addedToFeed' => [
                    'icon' => 'fa-chevron-down',
                    'text' => 'Added to feed',
                ],
                'deletedFeed' => [
                    'icon' => 'fa-times-circle',
                    'text' => 'Deleted feed',
                ],
                'disabledFeed' => [
                    'icon' => 'fa-times',
                    'text' => 'Disabled feed',
                ],
                'feedRequested' => [
                    'icon' => 'fa-bolt',
                    'text' => 'Feed requested',
                ],
                'serverNotResponding' => [
                    'icon' => 'fa-warning',
                    'text' => 'Server Not Responding',
                ],
                'enabledFeed' => [
                    'icon' => 'fa-lightbulb-o',
                    'text' => 'Enabled feed',
                ],
            ];
            ?>
            <!-- /.col-lg-8 -->
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bell fa-fw"></i> Notifications Panel
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="list-group">
                            <?php foreach ($this->logs as $logItem) { ?>
                                <a href="#" class="list-group-item">
                                    <i class="fa <?php echo $logTypes[$logItem['type']]['icon']; ?> fa-fw"></i> <?php echo $logTypes[$logItem['type']]['text']; ?>
                                    <span class="pull-right text-muted small"><em><?php echo $logItem['timestamp']; ?></em>
                                    </span>
                                </a>
                            <?php } ?>
                        </div>
                        <a href="#" class="btn btn-default btn-block">View All Alerts</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
