<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <?php require __DIR__ . '/navigation/top.phtml'; ?>
        <?php //require __DIR__ . '/navigation/side.phtml'; ?>
    </nav>
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Dashboard</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-rss fa-fw"></i> Feeds
                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    Actions
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="/create">Add feed</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover vertical-center">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Posts</th>
                                        <th>Admins</th>
                                        <th>Requests</th>
                                        <th>Url</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $i = 0; foreach ($this->feeds as $id => $feed) { $i++ ?>
                                        <tr class="<?php echo ['odd', 'even'][$i%2]; ?>">
                                            <td><?php echo htmlspecialchars($feed['name'], ENT_QUOTES, 'UTF-8'); ?></td>
                                            <td><?php echo $feed['posts']; ?></td>
                                            <td><?php echo count($feed['admins']); ?></td>
                                            <td><?php echo $feed['requests']; ?></td>
                                            <td><a href="/atom/<?php echo $id; ?>/name/feed.xml" class="btn btn-default" target="_blank"><i class="fa fa-rss fa-fw"></i></a></td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.panel -->
                <div class="chat-panel panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-comments fa-fw"></i>
                        <?php $feeds = $this->feeds; ?>
                        <?php if (count($feeds)) { ?>
                            <?php $feed = reset($feeds); ?>
                            Feed (<span class="feed-name"><?php echo htmlspecialchars($feed['name'], ENT_QUOTES, 'UTF-8'); ?></span>)
                        <?php } else { ?>
                            Feed (no feeds available)
                        <?php } ?>
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-chevron-down"></i>
                            </button>
                            <ul class="dropdown-menu slidedown">
                                <?php $i = 0; foreach ($this->feeds as $index => $feed) { $i++ ?>
                                    <?php if ($i === 2) { ?>
                                        <li class="divider"></li>
                                    <?php } ?>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-check-circle fa-fw"></i> <?php echo htmlspecialchars($feed['name'], ENT_QUOTES, 'UTF-8'); ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <ul class="chat">
                            <?php if (!count($feeds)) { ?>
                                <li class="left clearfix">
                                    <span class="chat-img pull-left">
                                        <img src="/images/github_icon.png" alt="GitHub Release" class="img-circle">
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font pull-left">No feeds added (yet)</strong>
                                            <small class="pull-right text-muted">
                                                <i class="fa fa-clock-o fa-fw"></i> now
                                            </small>
                                        </div>
                                        <p>
                                            You didn't add any feeds yet. <a href="/create">Create your first feed</a>!
                                        </p>
                                    </div>
                                </li>
                            <?php } else { ?>
                                <?php if (count($this->posts)) { ?>
                                    <?php foreach ($this->posts as $index => $post) { ?>
                                        <li class="<?php echo ['left', 'right'][$index % 2]; ?> clearfix">
                                            <span class="chat-img pull-<?php echo ['left', 'right'][$index % 2]; ?>">
                                                <img src="<?php echo htmlspecialchars($post['avatar_url'], ENT_QUOTES, 'UTF-8'); ?>" alt="GitHub Release" class="img-circle">
                                            </span>
                                            <div class="chat-body clearfix">
                                                <div class="header">
                                                    <strong class="primary-font pull-<?php echo ['left', 'right'][$index % 2]; ?>"><a href="<?php echo htmlspecialchars($post['url'], ENT_QUOTES, 'UTF-8'); ?>" target="_blank"><?php echo htmlspecialchars($post['repository'], ENT_QUOTES, 'UTF-8'); ?> <?php echo htmlspecialchars($post['version'], ENT_QUOTES, 'UTF-8'); ?></a></strong>
                                                    <small class="pull-<?php echo ['right', 'left'][$index % 2]; ?> text-muted">
                                                        <i class="fa fa-clock-o fa-fw"></i> <?php echo $post['timestamp']; ?>
                                                    </small>
                                                </div>
                                                <p>
                                                    <?php echo htmlspecialchars($post['content'], ENT_QUOTES, 'UTF-8'); ?>
                                                </p>
                                            </div>
                                        </li>
                                    <?php } ?>
                                <?php } else { ?>
                                    <li class="left clearfix">
                                        <span class="chat-img pull-left">
                                            <img src="/images/github_icon.png" alt="GitHub Release" class="img-circle">
                                        </span>
                                        <div class="chat-body clearfix">
                                            <div class="header">
                                                <strong class="primary-font pull-left">No posts found (yet)</strong>
                                                <small class="pull-right text-muted">
                                                    <i class="fa fa-clock-o fa-fw"></i> now
                                                </small>
                                            </div>
                                            <p>
                                                No posts for this feed has been found (yet). If this is a new feed it can take up to 10 minutes before the feed will be filled for the first time.
                                            </p>
                                        </div>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
            <?php
            $logTypes = [
                'newPost' => [
                    'icon' => 'fa-comment',
                    'text' => 'New Post',
                ],
                'newFeed' => [
                    'icon' => 'fa-rss',
                    'text' => 'New Feed',
                ],
                'addedToFeed' => [
                    'icon' => 'fa-chevron-down',
                    'text' => 'Added to feed',
                ],
                'deletedFeed' => [
                    'icon' => 'fa-times-circle',
                    'text' => 'Deleted feed',
                ],
                'disabledFeed' => [
                    'icon' => 'fa-times',
                    'text' => 'Disabled feed',
                ],
                'feedRequested' => [
                    'icon' => 'fa-bolt',
                    'text' => 'Feed requested',
                ],
                'serverNotResponding' => [
                    'icon' => 'fa-warning',
                    'text' => 'Server Not Responding',
                ],
                'enabledFeed' => [
                    'icon' => 'fa-lightbulb-o',
                    'text' => 'Enabled feed',
                ],
            ];
            ?>
            <!-- /.col-lg-8 -->
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bell fa-fw"></i> Notifications Panel
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="list-group">
                            <?php foreach ($this->logs as $logItem) { ?>
                                <a href="#" class="list-group-item">
                                    <i class="fa <?php echo $logTypes[$logItem['type']]['icon']; ?> fa-fw"></i> <?php echo $logTypes[$logItem['type']]['text']; ?>
                                    <span class="pull-right text-muted small"><em><?php echo $logItem['timestamp']; ?></em>
                                    </span>
                                </a>
                            <?php } ?>
                        </div>
                        <a href="#" class="btn btn-default btn-block">View All Alerts</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
