<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Feedr</title>
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
        <link href="/css/plugins/timeline.css" rel="stylesheet">
        <link href="/css/sb-admin-2.css" rel="stylesheet">
        <link href="/css/custom.css" rel="stylesheet">
        <link href="/css/plugins/morris.css" rel="stylesheet">
        <link href="/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?php echo $this->content; ?>
        <script src="/js/jquery.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/plugins/metisMenu/metisMenu.min.js"></script>
        <script src="/js/plugins/morris/raphael.min.js"></script>
        <script src="/js/plugins/morris/morris.min.js"></script>
        <script src="/js/plugins/morris/morris-data.js"></script>
        <script src="/js/sb-admin-2.js"></script>
        <script src="/js/custom.js"></script>
    </body>
</html>