<?php declare(strict_types=1); ?>
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            <?= $this->translate('page.dashboard.title'); ?>
            <small><?= $this->translate('page.dashboard.version'); ?> <?= $this->translate('site.version'); ?></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> <?= $this->translate('breadcrumbs.home'); ?></a></li>
            <li class="active"><?= $this->translate('page.dashboard.title'); ?></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-8">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?= $this->translate('page.dashboard.feeds.title'); ?></h3>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table no-margin">
                                <thead>
                                    <tr>
                                        <th><?= $this->translate('page.dashboard.feeds.column.name'); ?></th>
                                        <th><?= $this->translate('page.dashboard.feeds.column.posts'); ?></th>
                                        <th><?= $this->translate('page.dashboard.feeds.column.admins'); ?></th>
                                        <th><?= $this->translate('page.dashboard.feeds.column.requests'); ?></th>
                                        <th class="text-right"><?= $this->translate('page.dashboard.feeds.column.statistics'); ?></th>
                                        <th class="text-right"><?= $this->translate('page.dashboard.feeds.column.url'); ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><a href="pages/examples/invoice.html">Room 11 Regulars</a></td>
                                        <td>145</td>
                                        <td>12</td>
                                        <td>41575</td>
                                        <td class="text-right"><a href="/" class="btn btn-info btn-flat"><i class="fa fa-line-chart"></i></a></td>
                                        <td class="text-right"><a href="/" class="btn btn-warning btn-flat"><i class="fa">&#xf09e;</i></a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="box-footer clearfix">
                        <a href="/feeds/create" class="btn btn-sm btn-info btn-flat pull-left"><?= $this->translate('page.dashboard.feeds.new'); ?></a>
                        <a href="/feeds" class="btn btn-sm btn-default btn-flat pull-right"><?= $this->translate('page.dashboard.feeds.all'); ?></a>
                    </div>
                </div>
                <div class="box box-warning direct-chat">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-comments"></i> Room 11 Regulars</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-toggle="tooltip" title="<?= $this->translate('page.dashboard.feed.switch.title'); ?>" data-widget="chat-pane-toggle"><i class="fa fa-comments"></i></button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="direct-chat-messages">
                            <div class="direct-chat-msg">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name pull-left">kelunik/acme v0.2.1</span>
                                    <span class="direct-chat-timestamp pull-right">23 Jan 2:00 pm</span>
                                </div>
                                <img class="direct-chat-img" src="https://avatars.githubusercontent.com/u/2743004?v=3" alt="message user image">
                                <div class="direct-chat-text">
                                    <ul>
                                        <li>PHP 5.5 compatibility</li>
                                        <li>SAN certificates work now</li>
                                        <li>Improved error messages</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="direct-chat-msg right">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name pull-right">nikic/FastRoute v0.7.0</span>
                                    <span class="direct-chat-timestamp pull-left">23 Jan 2:05 pm</span>
                                </div>
                                <img class="direct-chat-img" src="https://avatars.githubusercontent.com/u/216080?v=3" alt="message user image">
                                <div class="direct-chat-text">
                                    <ul>
                                        <li>Add HHI file for Hack typechecking support. The HHI file requires HHVM 3.9 or newer.</li>
                                        <li>Fix support for empty routes.</li>
                                        <li>Improve error message if optional part is not at the end of a rout</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="direct-chat-contacts">
                            <ul class="contacts-list">
                                <li>
                                    <a href="#">
                                        <div class="contacts-list-info">
                                            <span class="contacts-list-name">
                                              Room 11 Regulars
                                              <small class="contacts-list-date pull-right"><span class="label label-info pull-right">10</span></small>
                                            </span>
                                            <span class="contacts-list-msg">PHP 5.5 compatibility. SAN certificates work now. Improved error...</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="contacts-list-info">
                                            <span class="contacts-list-name">
                                              Other feed
                                              <small class="contacts-list-date pull-right"><span class="label label-info pull-right">10</span></small>
                                            </span>
                                            <span class="contacts-list-msg">Lorem ipsum dolar sed amit...</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="box-footer">
                        <form action="#" method="post">
                            <div class="input-group">
                                <input type="text" name="message" placeholder="<?= $this->translate('page.dashboard.feed.filter.placeholder'); ?>" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-warning btn-flat"><?= $this->translate('page.dashboard.feed.filter.submit'); ?></button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-bell fa-fw"></i> <?= $this->translate('page.dashboard.notifications.title'); ?></h3>
                    </div>
                    <div class="box-body">
                        <ul class="products-list product-list-in-box">
                            <?php foreach ($this->notifications as $notification) { ?>
                                <li class="item">
                                    <div class="product-img">
                                        <i class="fa fa-unlock-alt fa-fw"></i>
                                    </div>
                                    <div class="product-info">
                                        <a href="/" class="product-title"><?= $this->translate('page.dashboard.notifications.' . $notification['action']); ?>
                                            <div class="time pull-right">
                                                <time datetime="2015-12-20T17:39:14Z" is="relative-time">Dec 20, 2015</time>
                                            </div>
                                            <span class="product-description">
                                              From IP address: <?= $this->escape($notification['data']['ip']); ?>
                                            </span>
                                        </a>
                                    </div>
                                </li>
                            <?php } ?>
                            <li class="item">
                                <div class="product-img">
                                    <i class="fa fa-bolt fa-fw"></i>
                                </div>
                                <div class="product-info">
                                    <a href="/" class="product-title"><?= $this->translate('page.dashboard.notifications.requested'); ?>
                                        <div class="time pull-right">
                                            <time datetime="2015-12-20T17:39:14Z" is="relative-time">Dec 20, 2015</time>
                                        </div>
                                        <span class="product-description">
                                          Room 11 Regulars
                                        </span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="box-footer text-center">
                        <a href="javascript::;" class="uppercase"><?= $this->translate('page.dashboard.notifications.view-more'); ?></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
