<?php declare(strict_types=1); ?>
<div class="login-box">
    <div class="login-logo">
        <b><?= $this->translate('site.title'); ?></b> <?= $this->translate('page.login.title'); ?>
    </div>
    <div class="login-box-body">
        <div class="row">
            <div class="col-xs-12">
                <a href="<?= $this->url; ?>" class="btn btn-primary btn-block btn-flat"><i class="fa fa-github"></i> <?= $this->translate('page.login.button'); ?></a>
            </div>
        </div>
        <div class="social-auth-links text-center">
            <p><?= $this->translate('page.login.privacy'); ?></p>
        </div>
    </div>
</div>
