<?php declare(strict_types=1); ?>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <strong><?= $this->translate('footer.project.github.%', ['https://github.com/Room-11/Feedr']); ?></strong>
        <b><?= $this->translate('footer.version.title'); ?></b> <?= $this->translate('site.version'); ?>
    </div>
    <strong><?= $this->translate('footer.theme.author'); ?></strong> <?= $this->translate('footer.theme.license'); ?>
</footer>
