<?php declare(strict_types=1); ?>
<header class="main-header">
    <a href="/" class="logo">
        <span class="logo-mini"><b>F</b>r</span>
        <span class="logo-lg"><b><?= $this->translate('site.title'); ?></b></span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only"><?= $this->translate('nav.hamburger.screenreader'); ?></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $this->escape($this->user->avatar_url); ?>" class="user-image" alt="<?= $this->escape($this->user->login); ?>">
                        <span class="hidden-xs"><?= $this->escape($this->user->login); ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="<?= $this->escape($this->user->avatar_url); ?>" class="img-circle" alt="<?= $this->escape($this->user->login); ?>">
                            <p>
                                <?= $this->escape($this->user->login); ?>
                                <?php if ($this->user->name) echo ' - ' . $this->escape($this->user->name); ?>
                                <small><?= $this->translate('nav.user.member-since.%', [(new \DateTime($this->user->created_at))->format('d-m-Y')]); ?></small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-right">
                                <form action="/logout" method="post">
                                    <input type="hidden" name="csrfToken" value="<?= base64_encode($this->csrfToken->get()); ?>">
                                    <button type="submit" class="btn btn-default btn-flat"><?= $this->translate('nav.logout.submit'); ?></button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
