<?php declare(strict_types=1); ?>
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $this->escape($this->user->avatar); ?>" class="img-circle" alt="<?= $this->escape($this->user->username); ?>">
            </div>
            <div class="pull-left info">
                <p><?= $this->escape($this->user->username); ?></p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="<?= $this->translate('nav.sidebar.search.placeholder'); ?>">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
          </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header"><?= $this->translate('nav.sidebar.main.title'); ?></li>
            <li <?php if ($this->request->matches('/')) echo 'class="active"'; ?>>
                <a href="/">
                    <i class="fa fa-dashboard"></i> <span><?= $this->translate('nav.sidebar.main.items.dashboard'); ?></span>
                </a>
            </li>
            <li class="treeview <?php if ($this->request->startsWith('/feeds')) echo 'active'; ?>">
                <a href="/feeds">
                    <i class="fa">&#xf09e;</i>
                    <span><?= $this->translate('nav.sidebar.main.items.feeds'); ?></span>
                    <span class="label label-primary pull-right">1</span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/feeds"><i class="fa fa-circle-o"></i> <?= $this->translate('nav.sidebar.main.items.feeds.yours'); ?></a></li>
                    <li><a href="/popular"><i class="fa fa-circle-o"></i> <?= $this->translate('nav.sidebar.main.items.feeds.popular'); ?></a></li>
                </ul>
            </li>
            <li>
                <a href="/statistics">
                    <i class="fa fa-line-chart"></i> <span><?= $this->translate('nav.sidebar.main.items.statistics'); ?></span>
                </a>
            </li>
            <li class="treeview">
                <a href="/notifications">
                    <i class="fa fa-bell-o"></i>
                    <span><?= $this->translate('nav.sidebar.main.items.notifications'); ?></span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="../charts/chartjs.html"><i class="fa fa-circle-o"></i> <?= $this->translate('nav.sidebar.main.items.notifications.requests'); ?></a></li>
                    <li><a href="../charts/morris.html"><i class="fa fa-circle-o"></i> <?= $this->translate('nav.sidebar.main.items.notifications.added'); ?></a></li>
                </ul>
            </li>
            <?php if ($this->user->isAdmin()) { ?>
                <li class="header"><?= $this->translate('nav.sidebar.admin.title'); ?></li>
                <li><a href="#"><i class="fa fa-users"></i> <span><?= $this->translate('nav.sidebar.admin.items.users'); ?></span></a></li>
                <li><a href="#"><i class="fa fa-warning text-red"></i> <span><?= $this->translate('nav.sidebar.admin.items.errors'); ?></span></a></li>
            <?php } ?>
        </ul>
    </section>
</aside>
