<?php declare(strict_types=1); ?>
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            <?= $this->translate('page.feeds.create.title'); ?>
            <small><?= $this->translate('page.feeds.create.subtitle'); ?></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> <?= $this->translate('breadcrumbs.home'); ?></a></li>
            <li><a href="/feeds"><?= $this->translate('page.feeds.create.title'); ?></a></li>
            <li class="active"><?= $this->translate('page.feeds.create.subtitle'); ?></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-8">
                <form action="/feeds/create" method="post" class="feed-form">
                    <input type="hidden" name="csrfToken" value="<?= base64_encode($this->csrfToken->get()); ?>">
                    <div class="box box-default">
                        <div class="box-header with-border">
                            <h3 class="box-title"><?= $this->translate('page.feeds.create.form.basic.title'); ?></h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label><?= $this->translate('page.feeds.create.form.basic.name.label'); ?></label>
                                        <div class="input-group">
                                            <div class="input-group-addon <?php if (!$this->form['name']->isValid()) echo 'has-error'; ?>">
                                                <i class="fa">&#xf09e;</i>
                                            </div>
                                            <input type="text" class="form-control" name="name" value="<?= $this->escape($this->form['name']->getValue()); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group <?php if (!$this->form['visibility']->isValid()) echo 'has-error'; ?>">
                                        <label><?= $this->translate('page.feeds.create.form.basic.visibility.label'); ?></label>
                                        <div class="form-group vertical-align-radios">
                                            <label class="horizontal-radio">
                                                <input type="radio" name="visibility" class="flat-blue" value="public" <?php if (!$this->form['visibility']->getValue() || $this->form['visibility']->getValue() === 'public') echo 'checked'; ?>>
                                                <?= $this->translate('page.feeds.create.form.basic.visibility.options.public'); ?>
                                            </label>
                                            <label class="horizontal-radio">
                                                <input type="radio" name="visibility" class="flat-blue" value="private" <?php if ($this->form['visibility']->getValue() === 'private') echo 'checked'; ?>>
                                                <?= $this->translate('page.feeds.create.form.basic.visibility.options.private'); ?>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>&nbsp;</label>
                                        <div class="form-group">
                                            <input type="submit" class="form-control btn btn-flat btn-success" name="name" value="<?= $this->translate('page.feeds.create.form.submit'); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row <?php if ($this->form['visibility']->getValue() !== 'private') echo 'collapse'; ?>">
                                <div class="col-md-6">
                                    <div class="form-group <?php if (!$this->form['password']->isValid()) echo 'has-error'; ?>">
                                        <label><?= $this->translate('page.feeds.create.form.basic.password.label'); ?></label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-lock"></i>
                                            </div>
                                            <input type="password" class="form-control" name="password" value="<?= $this->escape($this->form['password']->getValue()); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group <?php if (!$this->form['password2']->isValid()) echo 'has-error'; ?>">
                                        <label><?= $this->translate('page.feeds.create.form.basic.password2.label'); ?></label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-lock"></i>
                                            </div>
                                            <input type="password" class="form-control" name="password2" value="<?= $this->escape($this->form['password2']->getValue()); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box box-danger collapsed-box">
                        <div class="box-header">
                            <h3 class="box-title"><?= $this->translate('page.feeds.create.form.repos.title'); ?></h3>
                            <div class="box-tools pull-right">
                                <span data-toggle="tooltip" title="" class="badge bg-red" data-original-title="<?= $this->translate('page.feeds.create.form.repos.amount.%', [0]); ?>">0</span>
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-question"></i></button>
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                        <div class="box-body">
                            <input type="hidden" class="form-control" name="repositories" value="<?= $this->escape($this->form['repositories']->getValue()); ?>">
                            <div class="input-group">
                                <input class="form-control" name="repo-search" placeholder="<?= $this->translate('page.feeds.create.form.repos.add.placeholder'); ?>">
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-flat btn-success" data-action="repo-search"><i class="fa fa-fw fa-plus"></i></button>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover data-table repo-table">
                                    <thead>
                                        <tr>
                                            <th><?= $this->translate('page.feeds.create.form.repos.table.username.heading'); ?></th>
                                            <th><?= $this->translate('page.feeds.create.form.repos.table.repository.heading'); ?></th>
                                            <th><?= $this->translate('page.feeds.create.form.repos.table.url.heading'); ?></th>
                                            <th class="text-right"><?= $this->translate('page.feeds.create.form.repos.table.delete.heading'); ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Room-11</td>
                                            <td>Feedr</td>
                                            <td><a href="https://github.com/Room-11-Feedr" target="_blank">https://github.com/Room-11-Feedr</a></td>
                                            <td class="text-right"><button class="btn btn-danger btn-flat confirm"><i class="fa fa-trash-o"></i></button></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="box box-success collapsed-box">
                        <div class="box-header">
                            <h3 class="box-title"><?= $this->translate('page.feeds.create.form.admins.title'); ?></h3>
                            <div class="box-tools pull-right">
                                <span data-toggle="tooltip" title="" class="badge bg-green" data-original-title="<?= $this->translate('page.feeds.create.form.admins.amount.%', [0]); ?>">0</span>
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-question"></i></button>
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                        <div class="box-body">
                            <input type="hidden" class="form-control" name="administrators" value="<?= $this->escape($this->form['administrators']->getValue()); ?>">
                            <div class="input-group">
                                <input class="form-control" name="admin-search" placeholder="<?= $this->translate('page.feeds.create.form.admins.add.placeholder'); ?>">

                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-flat btn-success" data-action="admin-search"><i class="fa fa-fw fa-plus"></i></button>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover data-table admin-table">
                                    <thead>
                                        <tr>
                                            <th><?= $this->translate('page.feeds.create.form.admins.table.avatar.heading'); ?></th>
                                            <th><?= $this->translate('page.feeds.create.form.admins.table.username.heading'); ?></th>
                                            <th><?= $this->translate('page.feeds.create.form.admins.table.url.heading'); ?></th>
                                            <th class="text-right"><?= $this->translate('page.feeds.create.form.admins.table.delete.heading'); ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><img src="https://avatars.githubusercontent.com/u/1330296?v=3" class="user-image" alt="PeeHaa"></td>
                                            <td>PeeHaa</td>
                                            <td><a href="https://github.com/PeeHaa" target="_blank">https://github.com/PeeHaa</a></td>
                                            <td class="text-right"><button class="btn btn-danger btn-flat confirm"><i class="fa fa-trash-o"></i></button></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <div class="box box-warning direct-chat">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-comments"></i> <?= $this->translate('page.feeds.create.preview.title'); ?></h3>
                    </div>
                    <div class="box-body">
                        <div class="direct-chat-messages">
                            <div class="direct-chat-msg">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name pull-left">kelunik/acme v0.2.1</span>
                                    <span class="direct-chat-timestamp pull-right">23 Jan 2:00 pm</span>
                                </div>
                                <img class="direct-chat-img" src="https://avatars.githubusercontent.com/u/2743004?v=3" alt="message user image">
                                <div class="direct-chat-text">
                                    <ul>
                                        <li>PHP 5.5 compatibility</li>
                                        <li>SAN certificates work now</li>
                                        <li>Improved error messages</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="direct-chat-msg right">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name pull-right">nikic/FastRoute v0.7.0</span>
                                    <span class="direct-chat-timestamp pull-left">23 Jan 2:05 pm</span>
                                </div>
                                <img class="direct-chat-img" src="https://avatars.githubusercontent.com/u/216080?v=3" alt="message user image">
                                <div class="direct-chat-text">
                                    <ul>
                                        <li>Add HHI file for Hack typechecking support. The HHI file requires HHVM 3.9 or newer.</li>
                                        <li>Fix support for empty routes.</li>
                                        <li>Improve error message if optional part is not at the end of a rout</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="direct-chat-contacts">
                            <ul class="contacts-list">
                                <li>
                                    <a href="#">
                                        <div class="contacts-list-info">
                                            <span class="contacts-list-name">
                                              Room 11 Regulars
                                              <small class="contacts-list-date pull-right"><span class="label label-info pull-right">10</span></small>
                                            </span>
                                            <span class="contacts-list-msg">PHP 5.5 compatibility. SAN certificates work now. Improved error...</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="contacts-list-info">
                                            <span class="contacts-list-name">
                                              Other feed
                                              <small class="contacts-list-date pull-right"><span class="label label-info pull-right">10</span></small>
                                            </span>
                                            <span class="contacts-list-msg">Lorem ipsum dolar sed amit...</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
